apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radiofreerobotron-argo-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false, IncludeMutationWebhook=false
spec:
  project: default
  source:
    repoURL: 'https://github.com/janne808/radiofreerobotron-k8s.git'
    path: 'production-homelab'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: radiofreerobotron
  syncPolicy:
    syncOptions:
    - Createnamespace=true
    - ServerSideApply=false
    automated:
      selfHeal: true
      prune: true
