---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: janne808-regcred
  namespace: radiofreerobotron
spec:
  encryptedData:
    .dockerconfigjson: AgC5+nknsnF3N0CC0kHOtAI2qAwpTDdWxNp+suqzt36JaMwQV1bKS/WTGALrRJrlWw/Ts2unDFHbzvAV/+Rdp9EgG5JzeQMKhXZLe42MzUxa68NtgeAB1rMcwoRc42DSazezVsut3w/SZE7ZNUovRjJ1uYw/P6895PS5GqIs5Mv3AbFqAliHGbd3tHsWxElqa64WiReJkz1/PbUV+2/Yz6Suryqbnvx2MtVc2rnyjnjmxkyYCFbdyxr5BsWRNNmmLobuqm3R50bc9ScEH6IJldRcJ9xm5dq9xyBtVv97lFxF6Hnp/5UHoxyHkaJt89KEQXUdfp1U4e/imOlbMgPVFQC08JfJD3v2/uH7NF1tSeTlMIhau/yTQ1teBNxMojp/hKQ9sxqCpEnLmZ8bwDBgT2bZNnnlPu4nyzaSmmlA5OBmTTjV1o2K6I78OynBVSpwFZNhkT3Rpgw8M0/pVVXWT547D8QaVroVXH8iY619XiI76yiOtHDowCc+B+IH9QkfgkhqCN9jV9yQiwPqzQo9jWcpzzJ8HkAw6HwCHg0M09zSN4JuAvnv2t5cecWEssf4W5b5ogXmrq4+3BhKMhrtWe6eyl9EqOP/fOiru50Z7MFQunsTDGJ4/JGuy+Vqlc5rZGJUBxuvkjOQ2+AVbqSFzF6FhfVxf7QBC3lu1aXODiB9gJuIK3I0sumTRRn0csw3BgDiP6EBZLckxa/Rjw6f2IKsntMtzuvKbOMXs1HozHQlh2UWhHYBDwsX8a6pIk8n1Kwyu+ZjWUoRoCZZWnY8aguqhr1aIwQpXa4zm7vNLQ3WuO4cWSU2tQvOfPmG9uQCYJ18GVo=
  template:
    metadata:
      creationTimestamp: null
      name: janne808-regcred
      namespace: radiofreerobotron
    type: kubernetes.io/dockerconfigjson
