apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: mongodata
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: "16Gi"
