apiVersion: v1
kind: Service
metadata:
  name: icecast2
spec:
  selector:
    app: icecast2
  type: ClusterIP
  ports:
    - name: icecast2
      protocol: TCP
      port: 8000
      targetPort: icecast2
