apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      initContainers:
#      - name: init-nginx-web-root
#        image: busybox
#        volumeMounts:
#        - name: nginx-www-root
#          mountPath: /app
#        command: ['sh', '-c', 'wget https://stuff.radiofreerobotron.net/web.tar.gz --quiet -O - | tar -xzvf - -C /app']        
      containers:
        - name: web-root-sync
          image: k8s.gcr.io/git-sync:v3.1.6
          volumeMounts:
          - name: nginx-www-root
            mountPath: /tmp/git/app
          - name: k8s-deploy-key
            mountPath: /etc/git-secret
            readOnly: true
          env:
          - name: GIT_SYNC_REPO
            value: git://github.com/janne808/radiofreerobotron-web-root.git
          - name: GIT_SYNC_BRANCH
            value: main
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_DEST
            value: "app"
          - name: GIT_SYNC_SSH
            value: true
          - name: GIT_SSH_KEY_FILE
            value: "/etc/git-secret/id_k8s_deploy
        - name: nginx
          image: nginx:latest
          imagePullPolicy: "Always"
          volumeMounts:
            - name: nginx-www-root
              mountPath: /app
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/rfr.conf
              subPath: rfr.conf
            - name: nginx-config
              mountPath: /app/index.html
              subPath: index.html
          ports:
            - containerPort: 8000
              name: nginx
      imagePullSecrets:
        - name: janne808-regcred
      volumes:
        - name: nginx-www-root
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: k8s-deploy-key
          secret:
            secretName: k8s-deploy-key
