kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
       worker_connections  1024;
    }


    http {
       include       /etc/nginx/mime.types;
       default_type  application/octet-stream;

       log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';

       access_log  /var/log/nginx/access.log  main;

       sendfile        on;
       #tcp_nopush     on;

       keepalive_timeout  65;

       #gzip  on;

       include /etc/nginx/conf.d/*.conf;
    }
  rfr.conf: |
    server {
           listen 8000;
           listen [::]:8000;
           
           # don't try to redirect to 8000/8443 container ports
           port_in_redirect off;

           # set content-type charset
           charset utf-8;

           server_name radiofreerobotron.home.arpa www.radiofreerobotron.home.arpa;

           root /app/repo/;
           index index.html;

           location / {
                   # First attempt to serve request as file, then
                   # as directory, then fall back to displaying a 404.
                   try_files $uri $uri/ =404;
                   # Uncomment to enable naxsi on this location
                   # include /etc/nginx/naxsi.rules
           }

           # deny access to .htaccess files, if Apache's document root
           # concurs with nginx's one
           #
           location ~ /\.ht {
                   deny all;
           }

           # deny git files
           #
           location ~ /\.git {
                   deny all;
           }
           
           # deny git README.md file
           #
           location ~ /README.md {
                   deny all;
           }
    }
