kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
       worker_connections  1024;
    }


    http {
       include       /etc/nginx/mime.types;
       default_type  application/octet-stream;

       log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';

       access_log  /var/log/nginx/access.log  main;

       sendfile        on;
       #tcp_nopush     on;

       keepalive_timeout  65;

       #gzip  on;

       include /etc/nginx/conf.d/*.conf;
    }
  rfr.conf: |
    server {
           listen 8000;
           listen [::]:8000;
           
           # don't try to redirect to 8000/8443 container ports
           port_in_redirect off;

           # set content-type charset
           charset utf-8;

           server_name radiofreerobotron.home.arpa www.radiofreerobotron.home.arpa;

           root /app;
           index index.html;

           location / {
                   # First attempt to serve request as file, then
                   # as directory, then fall back to displaying a 404.
                   try_files $uri $uri/ =404;
                   # Uncomment to enable naxsi on this location
                   # include /etc/nginx/naxsi.rules
           }

           # deny access to .htaccess files, if Apache's document root
           # concurs with nginx's one
           #
           location ~ /\.ht {
                   deny all;
           }
    }
  index.html: |    
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "https://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
    <html>

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="Web crawling radio station, all content is crawled live from the internet">
    <meta property="og:description" content="Radio Free Robotron" />
    <meta name="keywords" content="industrial, techno, left-wing, leftist, anarchism, communism, electronic music, g-funk, boogie funk, modern funk, memphis rap, electro funk, electro, hip hop, hip-hop, dub, reggae, bass">
    <meta name="viewport" content="width=device-width, initial-scale=0.9">
    <link rel="stylesheet" type="text/css" href="freerobotron2.css" >
    <link type="text/css" href="jplayer.robotron.css" rel="stylesheet" />
    <title>Radio Free Robotron</title>

    <script src="jquery-1.11.1.min.js"></script>
    <script src="jquery.jplayer.js" type="text/javascript"></script>

    <script>
    $(document).ready(function(){
       $.ajaxSetup ({
           cache: false,
           scriptCharset: "utf-8",
           contentType: "application/json; charset=utf-8"       
       });

       function getRandomInt(min, max) {
          min = Math.ceil(min);
          max = Math.floor(max);
          return Math.floor(Math.random() * (max - min)) + min;
       }

       function updateScroll(){
          var element = document.getElementById("subcontainer");
          element.scrollTop = element.scrollHeight;
       }

       function getDateTime() {
        var date = new Date();

        var hour = date.getHours();
        hour = (hour < 10 ? "0" : "") + hour;

        var min  = date.getMinutes();
        min = (min < 10 ? "0" : "") + min;

        var sec  = date.getSeconds();
        sec = (sec < 10 ? "0" : "") + sec;

        return hour + ":" + min + ":" + sec;
       }

       var current = "";

       var nowplaying_update = function() {
          $.getJSON("/api/nowplaying", function(result){
             if(current != result.meta){
                current = result.meta;
                if(result.url){
                    $("#subcontainer").append("<p class=\"playlist\">" + getDateTime() + " <a class=\"selector\" href=\"" + result.url + "\">" + current + "</a></p>");
                }
                else{
                    $("#subcontainer").append("<p class=\"playlist\">" + getDateTime() + " " + current + "</p>");
                }
             }
             updateScroll();
          });
       };

       function instantiate_jplayer() {
          $("#jquery_jplayer_1").jPlayer({
             ready: function () {
                $(this).jPlayer("setMedia", {
                   mp3: "https://icecast.radiofreerobotron.home.arpa/robot2.mp3",
                   oga: "https://icecast.radiofreerobotron.home.arpa/robot.ogg",
                });
             },
             play: function () {
                $(this).jPlayer("play");
             },      
             pause: function () {
                $(this).jPlayer("clearMedia");
                $(this).jPlayer("destroy");
                instantiate_jplayer();
             },
             swfPath: "/swf",
             preload: "none",
             solution: "html,flash",
             supplied: "oga,mp3"
          });
       };

       var interval = 1000 * 5; // N seconds
       setInterval(nowplaying_update, interval);
       nowplaying_update();

       instantiate_jplayer();
    });
    </script>
    </head>
    <body>

    <div id="container">
    <div id="subcontainer">
    <pre id="rfrlogo">
                                                                         _______________
       r a d i o . f r e e                                               \             /
                                              /                          /            /                                 /
                __________/__                /_____     /__________________          /   __________/__                 /________________
           ____/            /    /          /     /____/__                /         /___/            /    /           /                /
       .        __.        /_______________/             .    /          /         /     __.        /________________/                /
      \\________\         /            __    /          /               /         /______\         /               '    //           /
                 \________\           \\________________\              /         /       \\________\                    /____________\
                                                                                /                                      
                                                                   /           /_                                 
                                                                  /           ___\
                                                                 /___________/
    </pre>
    <p class="playlist">[*] start log</p>
    </div>
    <div id="bottompanel">
    <div id="direct">
    Direct: <a class="selector2" href="http://icecast.radiofreerobotron.home.arpa/robot2.mp3">Mp3/128k</a> <a class="selector2" href="http://icecast.radiofreerobotron.home.arpa/robot.ogg">Ogg/128k</a> <a class="selector2" href="http://icecast.radiofreerobotron.home.arpa/robot_lq.ogg">Ogg/24k</a>
    </div>
    <div id="player">
      <div id="jquery_jplayer_1" class="jp-jplayer"></div>
      <div id="jp_container_1" class="jp-audio">
        <div class="jp-type-single">
          <div class="jp-gui jp-interface">
            <ul class="jp-controls">
              <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
              <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
    <!--
              <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
    -->
              <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
              <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
              <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
            </ul>
    <!--
            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>
    -->
            <div class="jp-volume-bar">
              <div class="jp-volume-bar-value"></div>
            </div>
            <div class="jp-time-holder">
              <div class="jp-current-time"></div>
    <!--
              <div class="jp-duration"></div>
    -->
    <!--
              <ul class="jp-toggles">
                <li><a href="javascript:;" class="jp-repeat" tabindex="1" title="repeat">repeat</a></li>
                <li><a href="javascript:;" class="jp-repeat-off" tabindex="1" title="repeat off">repeat off</a></li>
              </ul>
    -->
            </div>
          </div>
    <!--
          <div class="jp-title">
            <ul>
              <li>Bubble</li>
            </ul>
          </div>
    -->
          <div class="jp-no-solution">
            <span>Update Required</span>
            To play the media you will need to either update your browser to a recent version or update your <a href="https://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
          </div>
        </div>
      </div>
    </div>
    </div>

    </body>
    </html>
