apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web-root-sync
          image: k8s.gcr.io/git-sync:v3.1.5
          volumeMounts:
          - name: nginx-www-root
            mountPath: /tmp/git/app
          - name: k8s-deploy-key
            mountPath: /etc/deploy-key-secret
            readOnly: true
          args:
            - "-ssh"
            - "-repo=git@github.com:janne808/radiofreerobotron-web-root"
            - "-root=/tmp/git/app"
            - "-dest=repo"
            - "-branch=main"
            - "-depth=1"
            - "-ssh-known-hosts=false"
            - "-ssh-key-file=/etc/deploy-key-secret/id_k8s_deploy"
          securityContext:
            runAsUser: 65533
        - name: nginx
          image: nginx:latest
          imagePullPolicy: "Always"
          volumeMounts:
            - name: nginx-www-root
              mountPath: /app
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/rfr.conf
              subPath: rfr.conf
          ports:
            - containerPort: 8000
              name: nginx
      imagePullSecrets:
        - name: janne808-regcred
      securityContext:
        fsGroup: 65533
      volumes:
        - name: nginx-www-root
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: k8s-deploy-key
          secret:
            secretName: k8s-deploy-key
            defaultMode: 0400
